version: "3"
services:
  client:
#    image: nginx
    image: python:3-slim
    ports:
      - 8000:8000
    volumes:
      - ./client:/usr/share/nginx/html
    command: python -m http.server --bind 0.0.0.0 --directory /usr/share/nginx/html

  server:
    build:
      context: ./server
    ports:
      - 8001:8000
    volumes:
      - ./server:/app
